// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RuntimeMetrics is an autogenerated mock type for the RuntimeMetrics type
type RuntimeMetrics struct {
	mock.Mock
}

// SendMetrics provides a mock function with given fields:
func (_m *RuntimeMetrics) SendMetrics() {
	_m.Called()
}

// SendMetricsBatch provides a mock function with given fields:
func (_m *RuntimeMetrics) SendMetricsBatch() {
	_m.Called()
}

// UpdateMetrics provides a mock function with given fields:
func (_m *RuntimeMetrics) UpdateMetrics() {
	_m.Called()
}

type NewRuntimeMetricsT interface {
	mock.TestingT
	Cleanup(func())
}

// NewRuntimeMetrics creates a new instance of RuntimeMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRuntimeMetrics(t NewRuntimeMetricsT) *RuntimeMetrics {
	mock := &RuntimeMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
