// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// SendMetrics provides a mock function with given fields:
func (_m *Usecase) SendMetrics() {
	_m.Called()
}

// SendMetricsBatch provides a mock function with given fields:
func (_m *Usecase) SendMetricsBatch() {
	_m.Called()
}

// UpdateMetrics provides a mock function with given fields:
func (_m *Usecase) UpdateMetrics() {
	_m.Called()
}

type NewUsecaseT interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsecase creates a new instance of Usecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsecase(t NewUsecaseT) *Usecase {
	mock := &Usecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
