// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	devopsserver "github.com/IgorAleksandroff/musthave-devops/internal/api/services/devopsserver"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Update provides a mock function with given fields: url, data
func (_m *Client) Update(url string, data []devopsserver.Metrics) error {
	ret := _m.Called(url, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []devopsserver.Metrics) error); ok {
		r0 = rf(url, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClient(t mockConstructorTestingTNewClient) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
